---
  - apt: update_cache=yes cache_valid_time=3600
    become: yes
    when: ansible_pkg_mgr == "apt"
    tags: install

  - include_vars: "{{ item }}"
    with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
    when: virtualenv_package_name is not defined
    tags: install

  - name: install certbot (Debian jessie)
    include: debian-jessie.yml
    when: ansible_distribution == "Debian" and ansible_distribution_release == "jessie"

  - name: install certbot (Debian stretch)
    include: debian-stretch.yml
    when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"

  - name: install certbot (using pip)
    include: notdebian.yml
    when: ansible_distribution != "Debian"

  - name: Ensure webroot exists
    file:
      path: "{{ letsencrypt_webroot_path }}"
      state: directory
      follow: yes
    become: yes

  - name: Install renewal cron 
    become: yes
    cron:
      name: "Let's Encrypt Renewal"
      day: "{{ letsencrypt_renewal_frequency.day }}"
      hour: "{{ letsencrypt_renewal_frequency.hour }}"
      minute: "{{ letsencrypt_renewal_frequency.minute }}"
      job: "{{letsencrypt_path}} renew --quiet {{ letsencrypt_renewal_command_args }}"


  - include_tasks: domains.yml
    with_items:
      - "{{ letsencrypt_cert_domains }}"
    loop_control:
      loop_var: domain


